In [2]:
import pandas as pd

In [15]:
dataset_filepath = r"C:\Users\Ranjit\Desktop\Evening Training\student.csv"
df = pd.read_csv(dataset_filepath)
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [8]:
st  = "techie solution" 
st

'techie solution'

In [16]:
df.shape

(28, 6)

In [19]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   78.0      Graduate
1           2   Riya  21.0  Mumbai   85.0      Graduate
2           3  Rahul  19.0  Jaipur   67.0  Intermediate
3           4   Neha  22.0   Delhi    NaN      Graduate
4           5  Arjun  20.0     NaN   74.0  Intermediate

In [20]:
df.tail()

    student_id    name   age    city  marks     education
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [23]:
df.duplicated().sum()

3

In [30]:
df['age'].min()

19.0

In [31]:
df['age'].max()

23.0

In [33]:
df['marks'].mean()

77.72727272727273

In [34]:
## filter

In [35]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   78.0      Graduate
1           2   Riya  21.0  Mumbai   85.0      Graduate
2           3  Rahul  19.0  Jaipur   67.0  Intermediate
3           4   Neha  22.0   Delhi    NaN      Graduate
4           5  Arjun  20.0     NaN   74.0  Intermediate

In [37]:
df['education'].value_counts()

education
Graduate        14
Intermediate    11
High             3
Name: count, dtype: int64

In [41]:
graduate_student = df[df["education"] == "Graduate"]
graduate_student

    student_id    name   age    city  marks education
0            1    Amit  20.0   Delhi   78.0  Graduate
1            2    Riya  21.0  Mumbai   85.0  Graduate
3            4    Neha  22.0   Delhi    NaN  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
10          10   Sneha  22.0    Pune   76.0  Graduate
11          11   Vikas  21.0     NaN   82.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
16          16  Sunita  21.0   Delhi    NaN  Graduate
17          17   Manoj  23.0  Mumbai   77.0  Graduate
19          19   Ankit  22.0  Jaipur   68.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate
26          25   Nitin  22.0     NaN   75.0  Graduate

In [42]:
graduate_student.shape

(14, 6)

In [44]:
df[(df["education"] == "Graduate") &  (df['marks']>=85)]

    student_id    name   age    city  marks education
1            2    Riya  21.0  Mumbai   85.0  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate

In [45]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [47]:
df[df.duplicated()]

    student_id    name   age    city  marks     education
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [51]:
df.drop_duplicates(inplace=True)

In [52]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate

In [53]:
graduate_student

    student_id    name   age    city  marks education
0            1    Amit  20.0   Delhi   78.0  Graduate
1            2    Riya  21.0  Mumbai   85.0  Graduate
3            4    Neha  22.0   Delhi    NaN  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
10          10   Sneha  22.0    Pune   76.0  Graduate
11          11   Vikas  21.0     NaN   82.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
16          16  Sunita  21.0   Delhi    NaN  Graduate
17          17   Manoj  23.0  Mumbai   77.0  Graduate
19          19   Ankit  22.0  Jaipur   68.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate
26          25   Nitin  22.0     NaN   75.0  Graduate

In [59]:
graduate_student.to_csv("graduate_student_record.csv",index=False)

In [61]:
df.shape

(25, 6)

In [62]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate