In [3]:
import pandas as pd

In [32]:
dataset_filepath = r"C:\Users\Ranjit\Desktop\Evening Training\student.csv"
df = pd.read_csv(dataset_filepath)
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [8]:
st  = "techie solution" 
st

'techie solution'

In [16]:
df.shape

(28, 6)

In [19]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   78.0      Graduate
1           2   Riya  21.0  Mumbai   85.0      Graduate
2           3  Rahul  19.0  Jaipur   67.0  Intermediate
3           4   Neha  22.0   Delhi    NaN      Graduate
4           5  Arjun  20.0     NaN   74.0  Intermediate

In [20]:
df.tail()

    student_id    name   age    city  marks     education
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [23]:
df.duplicated().sum()

3

In [30]:
df['age'].min()

19.0

In [31]:
df['age'].max()

23.0

In [33]:
df['marks'].mean()

77.72727272727273

In [34]:
## filter

In [35]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   78.0      Graduate
1           2   Riya  21.0  Mumbai   85.0      Graduate
2           3  Rahul  19.0  Jaipur   67.0  Intermediate
3           4   Neha  22.0   Delhi    NaN      Graduate
4           5  Arjun  20.0     NaN   74.0  Intermediate

In [37]:
df['education'].value_counts()

education
Graduate        14
Intermediate    11
High             3
Name: count, dtype: int64

In [41]:
graduate_student = df[df["education"] == "Graduate"]
graduate_student

    student_id    name   age    city  marks education
0            1    Amit  20.0   Delhi   78.0  Graduate
1            2    Riya  21.0  Mumbai   85.0  Graduate
3            4    Neha  22.0   Delhi    NaN  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
10          10   Sneha  22.0    Pune   76.0  Graduate
11          11   Vikas  21.0     NaN   82.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
16          16  Sunita  21.0   Delhi    NaN  Graduate
17          17   Manoj  23.0  Mumbai   77.0  Graduate
19          19   Ankit  22.0  Jaipur   68.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate
26          25   Nitin  22.0     NaN   75.0  Graduate

In [42]:
graduate_student.shape

(14, 6)

In [44]:
df[(df["education"] == "Graduate") &  (df['marks']>=85)]

    student_id    name   age    city  marks education
1            2    Riya  21.0  Mumbai   85.0  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate

In [45]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [47]:
df[df.duplicated()]

    student_id    name   age    city  marks     education
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [51]:
df.drop_duplicates(inplace=True)

In [52]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate

In [53]:
graduate_student

    student_id    name   age    city  marks education
0            1    Amit  20.0   Delhi   78.0  Graduate
1            2    Riya  21.0  Mumbai   85.0  Graduate
3            4    Neha  22.0   Delhi    NaN  Graduate
5            6   Pooja  21.0    Pune   88.0  Graduate
7            8  Anjali  23.0   Delhi   91.0  Graduate
10          10   Sneha  22.0    Pune   76.0  Graduate
11          11   Vikas  21.0     NaN   82.0  Graduate
14          14  Kavita  22.0  Jaipur   89.0  Graduate
16          16  Sunita  21.0   Delhi    NaN  Graduate
17          17   Manoj  23.0  Mumbai   77.0  Graduate
19          19   Ankit  22.0  Jaipur   68.0  Graduate
20          20   Divya  21.0    Pune   90.0  Graduate
25          24   Payal  21.0    Pune   86.0  Graduate
26          25   Nitin  22.0     NaN   75.0  Graduate

In [59]:
graduate_student.to_csv("graduate_student_record.csv",index=False)

In [61]:
df.shape

(25, 6)

In [62]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate

### missing value handling

In [ ]:
# 
1. delete record 
2. impute the value

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
3            4    Neha  22.0   Delhi    NaN      Graduate
4            5   Arjun  20.0     NaN   74.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
6            7   Karan   NaN  Mumbai   69.0          High
7            8  Anjali  23.0   Delhi   91.0      Graduate
8            9   Rohit  20.0  Jaipur    NaN  Intermediate
9            9   Rohit  20.0  Jaipur    NaN  Intermediate
10          10   Sneha  22.0    Pune   76.0      Graduate
11          11   Vikas  21.0     NaN   82.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
15          15  Deepak   NaN    Pune   71.0          High
16          16  Sunita  21.0   Delhi    NaN      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
18          18   Rekha  20.0     NaN   83.0  Intermediate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
22          22   Seema   NaN  Mumbai   80.0          High
23          23  Rakesh  20.0  Jaipur    NaN  Intermediate
24          23  Rakesh  20.0  Jaipur    NaN  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
26          25   Nitin  22.0     NaN   75.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [8]:
df.isnull().sum()

student_id    0
name          0
age           3
city          4
marks         6
education     0
dtype: int64

In [9]:
df.isnull().sum().sum()

13

In [15]:
df[df["age"].isnull()]

    student_id    name  age    city  marks education
6            7   Karan  NaN  Mumbai   69.0      High
15          15  Deepak  NaN    Pune   71.0      High
22          22   Seema  NaN  Mumbai   80.0      High

In [ ]:
df.dropna(inplace=True)  # rows

In [22]:
df

    student_id    name   age    city  marks     education
0            1    Amit  20.0   Delhi   78.0      Graduate
1            2    Riya  21.0  Mumbai   85.0      Graduate
2            3   Rahul  19.0  Jaipur   67.0  Intermediate
5            6   Pooja  21.0    Pune   88.0      Graduate
7            8  Anjali  23.0   Delhi   91.0      Graduate
10          10   Sneha  22.0    Pune   76.0      Graduate
12          12   Meena  19.0  Mumbai   64.0  Intermediate
13          13  Sachin  20.0   Delhi   73.0  Intermediate
14          14  Kavita  22.0  Jaipur   89.0      Graduate
17          17   Manoj  23.0  Mumbai   77.0      Graduate
19          19   Ankit  22.0  Jaipur   68.0      Graduate
20          20   Divya  21.0    Pune   90.0      Graduate
21          21    Ajay  19.0   Delhi   72.0  Intermediate
25          24   Payal  21.0    Pune   86.0      Graduate
27          21    Ajay  19.0   Delhi   72.0  Intermediate

In [30]:
df.dropna(axis="rows",inplace=True)  
# 0 --> rows 
# 1 --> columns

In [34]:
df.fillna("claude")

    student_id    name     age    city   marks     education
0            1    Amit    20.0   Delhi    78.0      Graduate
1            2    Riya    21.0  Mumbai    85.0      Graduate
2            3   Rahul    19.0  Jaipur    67.0  Intermediate
3            4    Neha    22.0   Delhi  claude      Graduate
4            5   Arjun    20.0  claude    74.0  Intermediate
5            6   Pooja    21.0    Pune    88.0      Graduate
6            7   Karan  claude  Mumbai    69.0          High
7            8  Anjali    23.0   Delhi    91.0      Graduate
8            9   Rohit    20.0  Jaipur  claude  Intermediate
9            9   Rohit    20.0  Jaipur  claude  Intermediate
10          10   Sneha    22.0    Pune    76.0      Graduate
11          11   Vikas    21.0  claude    82.0      Graduate
12          12   Meena    19.0  Mumbai    64.0  Intermediate
13          13  Sachin    20.0   Delhi    73.0  Intermediate
14          14  Kavita    22.0  Jaipur    89.0      Graduate
15          15  Deepak  claude    Pune    71.0          High
16          16  Sunita    21.0   Delhi  claude      Graduate
17          17   Manoj    23.0  Mumbai    77.0      Graduate
18          18   Rekha    20.0  claude    83.0  Intermediate
19          19   Ankit    22.0  Jaipur    68.0      Graduate
20          20   Divya    21.0    Pune    90.0      Graduate
21          21    Ajay    19.0   Delhi    72.0  Intermediate
22          22   Seema  claude  Mumbai    80.0          High
23          23  Rakesh    20.0  Jaipur  claude  Intermediate
24          23  Rakesh    20.0  Jaipur  claude  Intermediate
25          24   Payal    21.0    Pune    86.0      Graduate
26          25   Nitin    22.0  claude    75.0      Graduate
27          21    Ajay    19.0   Delhi    72.0  Intermediate

In [38]:
df["city"].fillna("claude",inplace=True)

In [40]:
df["marks"].fillna(65.0,inplace=True)

C:\Users\Ranjit\AppData\Local\Temp\ipykernel_10216\583972237.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(65.0,inplace=True)

In [42]:
df.isnull().sum()

student_id    0
name          0
age           3
city          0
marks         0
education     0
dtype: int64

In [44]:
df['age'].mean()

20.72

In [47]:
df['age']  =   df['age'].fillna(df['age'].mean())

In [51]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   78.0      Graduate
1           2   Riya  21.0  Mumbai   85.0      Graduate
2           3  Rahul  19.0  Jaipur   67.0  Intermediate
3           4   Neha  22.0   Delhi   65.0      Graduate
4           5  Arjun  20.0  claude   74.0  Intermediate

In [52]:
df['marks'] = df['marks']+5

In [53]:
df.head()

   student_id   name   age    city  marks     education
0           1   Amit  20.0   Delhi   83.0      Graduate
1           2   Riya  21.0  Mumbai   90.0      Graduate
2           3  Rahul  19.0  Jaipur   72.0  Intermediate
3           4   Neha  22.0   Delhi   70.0      Graduate
4           5  Arjun  20.0  claude   79.0  Intermediate

In [55]:
df['original_marks']  = df['marks'] - 5

In [56]:
df.head()

   student_id   name   age    city  marks     education  original_marks
0           1   Amit  20.0   Delhi   83.0      Graduate            78.0
1           2   Riya  21.0  Mumbai   90.0      Graduate            85.0
2           3  Rahul  19.0  Jaipur   72.0  Intermediate            67.0
3           4   Neha  22.0   Delhi   70.0      Graduate            65.0
4           5  Arjun  20.0  claude   79.0  Intermediate            74.0

In [60]:
df['claude'] = None

In [63]:
df.columns = ['student_id', 'name', 'age', 'city', 'marks', 'education',
       'original_marks', 'teddy']

In [65]:
df.dropna(axis=1)

    student_id    name    age    city  marks     education  original_marks
0            1    Amit  20.00   Delhi   83.0      Graduate            78.0
1            2    Riya  21.00  Mumbai   90.0      Graduate            85.0
2            3   Rahul  19.00  Jaipur   72.0  Intermediate            67.0
3            4    Neha  22.00   Delhi   70.0      Graduate            65.0
4            5   Arjun  20.00  claude   79.0  Intermediate            74.0
5            6   Pooja  21.00    Pune   93.0      Graduate            88.0
6            7   Karan  20.72  Mumbai   74.0          High            69.0
7            8  Anjali  23.00   Delhi   96.0      Graduate            91.0
8            9   Rohit  20.00  Jaipur   70.0  Intermediate            65.0
9            9   Rohit  20.00  Jaipur   70.0  Intermediate            65.0
10          10   Sneha  22.00    Pune   81.0      Graduate            76.0
11          11   Vikas  21.00  claude   87.0      Graduate            82.0
12          12   Meena  19.00  Mumbai   69.0  Intermediate            64.0
13          13  Sachin  20.00   Delhi   78.0  Intermediate            73.0
14          14  Kavita  22.00  Jaipur   94.0      Graduate            89.0
15          15  Deepak  20.72    Pune   76.0          High            71.0
16          16  Sunita  21.00   Delhi   70.0      Graduate            65.0
17          17   Manoj  23.00  Mumbai   82.0      Graduate            77.0
18          18   Rekha  20.00  claude   88.0  Intermediate            83.0
19          19   Ankit  22.00  Jaipur   73.0      Graduate            68.0
20          20   Divya  21.00    Pune   95.0      Graduate            90.0
21          21    Ajay  19.00   Delhi   77.0  Intermediate            72.0
22          22   Seema  20.72  Mumbai   85.0          High            80.0
23          23  Rakesh  20.00  Jaipur   70.0  Intermediate            65.0
24          23  Rakesh  20.00  Jaipur   70.0  Intermediate            65.0
25          24   Payal  21.00    Pune   91.0      Graduate            86.0
26          25   Nitin  22.00  claude   80.0      Graduate            75.0
27          21    Ajay  19.00   Delhi   77.0  Intermediate            72.0

In [67]:
df['teddy'] = 1

In [ ]:
df.dropna()

,student_id,name,age,city,marks,education,original_marks,teddy
0,1,Amit,20.00,Delhi,83.0,Graduate,78.0,1
1,2,Riya,21.00,Mumbai,90.0,Graduate,85.0,1
2,3,Rahul,19.00,Jaipur,72.0,Intermediate,67.0,1
3,4,Neha,22.00,Delhi,70.0,Graduate,65.0,1
4,5,Arjun,20.00,claude,79.0,Intermediate,74.0,1
5,6,Pooja,21.00,Pune,93.0,Graduate,88.0,1
6,7,Karan,20.72,Mumbai,74.0,High,69.0,1
7,8,Anjali,23.00,Delhi,96.0,Graduate,91.0,1
8,9,Rohit,20.00,Jaipur,70.0,Intermediate,65.0,1
9,9,Rohit,20.00,Jaipur,70.0,Intermediate,65.0,1
10,10,Sneha,22.00,Pune,81.0,Graduate,76.0,1
11,11,Vikas,21.00,claude,87.0,Graduate,82.0,1
12,12,Meena,19.00,Mumbai,69.0,Intermediate,64.0,1
13,13,Sachin,20.00,Delhi,78.0,Intermediate,73.0,1
14,14,Kavita,22.00,Jaipur,94.0,Graduate,89.0,1
15,15,Deepak,20.72,Pune,76.0,High,71.0,1
16,16,Sunita,21.00,Delhi,70.0,Graduate,65.0,1
17,17,Manoj,23.00,Mumbai,82.0,Graduate,77.0,1
18,18,Rekha,20.00,claude,88.0,Intermediate,83.0,1
19,19,Ankit,22.00,Jaipur,73.0,Graduate,68.0,1
20,20,Divya,21.00,Pune,95.0,Graduate,90.0,1
21,21,Ajay,19.00,Delhi,77.0,Intermediate,72.0,1
22,22,Seema,20.72,Mumbai,85.0,High,80.0,1
23,23,Rakesh,20.00,Jaipur,70.0,Intermediate,65.0,1
24,23,Rakesh,20.00,Jaipur,70.0,Intermediate,65.0,1
25,24,Payal,21.00,Pune,91.0,Graduate,86.0,1
26,25,Nitin,22.00,claude,80.0,Graduate,75.0,1
27,21,Ajay,19.00,Delhi,77.0,Intermediate,72.0,1

In [74]:
df.drop(["teddy"],axis=1,inplace=True)

In [77]:
df.drop([2])

    student_id    name    age    city  marks     education  original_marks
0            1    Amit  20.00   Delhi   83.0      Graduate            78.0
1            2    Riya  21.00  Mumbai   90.0      Graduate            85.0
3            4    Neha  22.00   Delhi   70.0      Graduate            65.0
4            5   Arjun  20.00  claude   79.0  Intermediate            74.0
5            6   Pooja  21.00    Pune   93.0      Graduate            88.0
6            7   Karan  20.72  Mumbai   74.0          High            69.0
7            8  Anjali  23.00   Delhi   96.0      Graduate            91.0
8            9   Rohit  20.00  Jaipur   70.0  Intermediate            65.0
9            9   Rohit  20.00  Jaipur   70.0  Intermediate            65.0
10          10   Sneha  22.00    Pune   81.0      Graduate            76.0
11          11   Vikas  21.00  claude   87.0      Graduate            82.0
12          12   Meena  19.00  Mumbai   69.0  Intermediate            64.0
13          13  Sachin  20.00   Delhi   78.0  Intermediate            73.0
14          14  Kavita  22.00  Jaipur   94.0      Graduate            89.0
15          15  Deepak  20.72    Pune   76.0          High            71.0
16          16  Sunita  21.00   Delhi   70.0      Graduate            65.0
17          17   Manoj  23.00  Mumbai   82.0      Graduate            77.0
18          18   Rekha  20.00  claude   88.0  Intermediate            83.0
19          19   Ankit  22.00  Jaipur   73.0      Graduate            68.0
20          20   Divya  21.00    Pune   95.0      Graduate            90.0
21          21    Ajay  19.00   Delhi   77.0  Intermediate            72.0
22          22   Seema  20.72  Mumbai   85.0          High            80.0
23          23  Rakesh  20.00  Jaipur   70.0  Intermediate            65.0
24          23  Rakesh  20.00  Jaipur   70.0  Intermediate            65.0
25          24   Payal  21.00    Pune   91.0      Graduate            86.0
26          25   Nitin  22.00  claude   80.0      Graduate            75.0
27          21    Ajay  19.00   Delhi   77.0  Intermediate            72.0