In [1]:
print("hiii")

hiii

In [ ]:
pip3 install pandas

In [7]:
import pandas as pd 
print("imported")

imported

In [5]:
student_data = {"name":['claude','jack','teddy'],
                "age":[24,26,25],
                "city":["agra","mummai","goa"]}
print(student_data)
print(type(student_data))

{'name': ['claude', 'jack', 'teddy'], 'age': [24, 26, 25], 'city': ['agra', 'mummai', 'goa']}
<class 'dict'>

In [ ]:
1. series 
2. dataframe

In [9]:
df = pd.DataFrame(student_data)

In [11]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [14]:
ser = df["name"]

In [15]:
ser

0    claude
1      jack
2     teddy
Name: name, dtype: object

In [16]:
df

     name  age    city
0  claude   24    agra
1    jack   26  mummai
2   teddy   25     goa

In [17]:
print(type(ser))

<class 'pandas.core.series.Series'>

In [ ]:
df.name  # df["name"]

0    claude
1      jack
2     teddy
Name: name, dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [27]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [28]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [ ]:
df.shape   # (rows, columns)

(3, 3)

In [30]:
df

     name  age    city
0  claude   24    agra
1    jack   26  mummai
2   teddy   25     goa

In [33]:
df[["age","name"]]

   age    name
0   24  claude
1   26    jack
2   25   teddy

In [34]:
df

     name  age    city
0  claude   24    agra
1    jack   26  mummai
2   teddy   25     goa

In [35]:
# loc and iloc 
df.iloc[1]

name      jack
age         26
city    mummai
Name: 1, dtype: object